### ISSUE TITLE
Link out of an engine?

### ISSUE THREAD

**Issue by dfreeman** [dgeb/ember-engines#57] opened 2016-01-26 16:44 UTC
Currently, all transition destinations in a routable engine are automatically relative to the engine's mount point, which makes perfect sense for the common case. As we're considering what our monolith might look like in an engines world, though, it's becoming clear that we have a set of core entities in our domain that most engines are going to want to be able to reference and potentially link out to.

I could imagine exposing the actual names of such engine-external routes via a service or some other dedicated configuration, and then just mocking out simple placeholder routes and pointing to those in the engine's dummy app during testing and isolated development.

To actually transition to these routes, though, we'd need a way to opt out of the automatic prefixing in  those specific `{{link-to}}` and `transitionTo()` invocations. Is this a use case that makes sense to support?

**Comment by dgeb** [comment] 2016-01-26 18:00
Thanks for raising this. There are definitely going to be situations in which engines will know exactly where they're being mounted, although this should not be the default case (as you point out).

@rwjblue and I have discussed the possibility of enabling links to parent routes through a custom `{{link-to-parent}}` helper (or similar). It's certainly technically possible, although we need to be careful to not encourage anti-patterns.

**Comment by mike183** [comment] 2016-01-27 13:06
This is something that I had been thinking about, but I think @dgeb's and @rwjblue's suggestion of something similar to a `{{link-to-parent}}` helper would be a better alternative as it would also make templates more explicit.

Something else that may also be worth considering, would the `{{link-to-parent}}` helper allow you to transition to routes from multiple levels up and not a direct parent? Or is that something that should be discouraged?

**Comment by stefanpenner** [comment] 2016-01-27 15:49
I would like to propose his be an independent RFC as many details need to be fleshed out

**Comment by trentmwillis** [comment] 2016-02-03 16:52
Would love to see this feature added as I think it fits a pattern we see frequently. Any application with a "tabbed" interface could potentially want each tab to be a separate Engine but would almost certainly have flows that would link between tabs/engines.

In that regard, I think `{{link-to-parent}}` is semantically confusing, does that mean you can only link to your parent application/engine? What about into a sibling engine? My initial thought is instead to name it `{{link-to-external}}` as in all cases you're going to something external to the Engine. But this is kind of a minor point.

Maybe I missed it, but is there any point in the RFC that outlines the expected behavior/scoping of links/routing within an Engine?

**Comment by stefanpenner** [comment] 2016-02-04 22:51
question that need answering in the RFC

how does one link to engines which have not yet been loaded ?

* how do QP support this case
* how do current/loading/active etc support this case.

**Comment by nathanhammond** [comment] 2016-02-04 23:07
@trentmwillis @stefanpenner @rwjblue and I all had a conversation on Slack. Conclusion: this is a feature, not a bug.

The isolation that exists right now helps us avoid cross-linking, which protects us from having to solve the async engines story. Implementing linking outside of the current engine is dangerous as the target could be literally anything, and you have no idea if that async engine has landed.

**Comment by nathanhammond** [comment] 2016-02-04 23:13
See also: https://github.com/dgeb/ember-engines/issues/22

**Comment by trentmwillis** [comment] 2016-02-17 23:23
RFC for this is up at emberjs/rfcs#122.

**Comment by dgeb** [comment] 2016-05-03 19:18
Closed via #75

**Closed by dgeb** 2016-05-03 19:18 UTC
