### ISSUE TITLE
link-to-external `targetRouteName` is undefined

### ISSUE THREAD

**Issue by jbailey4** [dgeb/ember-engines#264] opened 2016-11-17 19:56 UTC
Within an engine the `link-to-external` component is throwing an error when attempting to get the external route. After stepping into the code it looks like the `targetRouteName` is `undefined` on the component. So this causes the `_getExternalRoute` to fail the external route lookup on the provided dependencies.

<img width="603" alt="screen shot 2016-11-17 at 2 43 46 pm" src="https://cloud.githubusercontent.com/assets/4117594/20404805/79a51cb0-acd4-11e6-96a9-533e642354f0.png">

**Comment by nathanhammond** [comment] 2016-11-17 20:00
This is likely not a bug, but a configuration problem in your application. We know this to work because it's used in production at LI.

Please stop by [#-ember-engines](https://embercommunity.slack.com/messages/-ember-engines/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and seek help from the wonderful people in our community!

I'm closing this issue for now. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

**Comment by nathanhammond** [comment] 2016-11-17 20:01
(Or, if it is a bug, get us a reproduction!)

**Closed by nathanhammond** 2016-11-17 20:00 UTC

**Comment by jbailey4** [comment] 2016-11-17 20:06
@nathanhammond Yeah that could be it, not ruling that out. I did noticed changing [this line](https://github.com/dgeb/ember-engines/blob/master/addon/-private/link-to-external-component.js#L12) to the `willRender` hook worked. Not sure if something changed with the link-to component ember upstream. I'll get a repro up asap. My work's proxy blocks pushing up to github 👎

**Comment by Nuzsk** [comment] 2016-11-21 12:49
@nathanhammond 
It's a bug, because ember-glimmer expects of glimmer-2 availability in 2.9 ember version, but glimmer-2 not included in 2.9 ember.

https://github.com/dgeb/ember-engines/commit/136f62c5fe79baf88a397af7c68ea748eca5add6
http://emberjs.com/blog/2016/10/17/ember-2-9-released.html#toc_ember-js-2-9

**Comment by rwjblue** [comment] 2016-11-21 13:02
Agreed, submitted https://github.com/dgeb/ember-engines/pull/270 to address. Thanks for tracking it down!

Robert Jackson

-- twitter: rwjblue
-- github: rjackson

**Comment by nathanhammond** [comment] 2016-11-21 18:15
Ah, damn. That whole Glimmer release switcheroo. 😜 Thanks for getting this right.

**Comment by crodriguez1a** [comment] 2017-05-31 16:35
@jbailey4 Hm, I'm seeing this with 2.13. Am I not configuring properly in `app.js`? It seems as though there aren't any external routes registered.

<img width="461" alt="screen shot 2017-05-31 at 12 31 37 pm" src="https://cloud.githubusercontent.com/assets/3610417/26642898/740acfd0-45fd-11e7-873f-abb4b3a6bb25.png">

**Comment by crodriguez1a** [comment] 2017-05-31 17:00
@jbailey4 Actually, I can see the dependencies registered on the mount point, so config must be fine. Separately, the component hook seems fine for the post glimmer world.   I'll dig in to see if I can't find some other cause.

**Comment by crodriguez1a** [comment] 2017-05-31 17:17
@jbailey4  I'll just keep documenting what I find. If it turns out to be unhelpful, I'll delete all this.  Here's what I found (and its really weird).

```es6
// Using Ember.get => undefined
get(this, 'targetRouteName')

// Using plain old property access => MyTargetRoute
this.targetRouteName
```

https://github.com/ember-engines/ember-engines/blob/da05713bfbd7ca5d415623b1bb4160c34c842be0/addon/components/link-to-external-component.js#L18

Has anything changed about Ember.get? Going there next.

cc/ @nathanhammond @rwjblue

**Comment by crodriguez1a** [comment] 2017-05-31 17:26
@jbailey4 Okay, well i don't know what changed, but I have a solution.

`import get from 'ember-metal/get';`  then `get(this, 'targetRouteName')` works fine.

Not entirely sure why. @nathanhammond  @rwjblue Let me know if I should submit a PR, or I'll also settle for the consolation prize of know why this broke.

**Comment by crodriguez1a** [comment] 2017-05-31 18:08
@jbailey4 Okay, here's the final piece (it combination with above) and now it works without throwing.

It seems that, in the engine instance, `_externalRoutes` is just not a thing [here](https://github.com/ember-engines/ember-engines/blob/master/addon/-private/engine-instance-ext.js#L118) 

When you dig down to `dependencies.externalRoutes`, then you're good.

```es6
  _getExternalRoute(routeName) {
    const route = this.dependencies.externalRoutes[routeName];
  
  // etc.
  }
```

**Comment by trentmwillis** [comment] 2017-06-01 01:22
@crodriguez1a what version of `ember-engines` are you using with `ember@2.13`? You shouldn't need to dig that far into the code.

**Comment by crodriguez1a** [comment] 2017-06-01 09:13
@trentmwillis  I'm using `0.5.4`. Yeah, my first instinct was just a bad configuration. I'm probably missing something obvious here.

**Comment by trentmwillis** [comment] 2017-06-01 15:12
Interesting, since the root cause is likely different from this issue, if you could open a new issue with a reproduction it would be appreciated.

**Comment by crodriguez1a** [comment] 2017-06-01 15:25
@trentmwillis 👍 Will do.

**Comment by crodriguez1a** [comment] 2017-06-01 16:36
@trentmwillis Reproducing lead me to the issue. I was simply missing the config in `engine.js`. If you miss the `app.js` config, it throws `A dependency mapping for 'externalRoutes.home' must be declared on this engine's parent.`. Conversely, missing the `engine.js` config surfaces as `Cannot read property 'MyTargetRoute' of undefined
    at Class._getExternalRoute`. I'll go ahead and clean up this thread.

**Comment by crodriguez1a** [comment] 2017-06-03 11:38
Hey @trentmwillis, one I thing I did find is that it does seem possible to have a single dependency declaration, and have the engine instance be aware. Any reason not to have just the one config at the consuming app? Just curious.
