### ISSUE TITLE
Defining child routes as externalRoutes

### ISSUE THREAD

**Issue by selvaa89** [dgeb/ember-engines#245] opened 2016-10-28 06:08 UTC
If I want to link a child route as an externalRoute in an engine, I have to configure it as externalRoute even if the parent route is already configured as externalRoute.

I think it is annoying to define child routes separately.

**Comment by nathanhammond** [comment] 2016-10-28 08:27
This is intentional and not a bug. We don't want to allow the engine to know anything about the route structure of its host. Engines are an _isolation_ primitive which means that all dependencies and interfaces must be specified–including every route you must link to.

[There has already been a _long_ discussion on this topic.](https://github.com/emberjs/rfcs/pull/122)

I'm closing this. Please stop by [#-ember-engines](https://embercommunity.slack.com/messages/-ember-engines/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if you wish to discuss more. 😄

**Closed by nathanhammond** 2016-10-28 08:27 UTC
