### ISSUE TITLE
Fix link-to-external for integration tests

### ISSUE THREAD

**Issue by trentmwillis** [dgeb/ember-engines#124] opened 2016-06-02 17:08 UTC
Since [`link-to-external` is currently registered manually](https://github.com/dgeb/ember-engines/blob/6f0e903b7153f794b1c9b3a20a576a0c4b7f25be/addon/-private/engine-ext.js#L89), integration tests that test components using `link-to-external` wind up having problems since it can't be resolved.

One current solution is for developers to manually import the component and register it, which requires reaching into the `-private` internals of `ember-engines` (obviously non-ideal).

I'm unsure of the best way to solve this issue. My thinking currently is that the best way would be to enable `ember-engines/resolver` to have knowledge of resolving it's special components (currently only the modified `link-to` and `link-to-external`).

**Comment by nickiaconis** [comment] 2016-09-12 22:17
I tried the suggested workaround, like so:

```javascript
import LinkToExternalComponent from 'ember-engines/-private/link-to-external-component';

module('my-component', 'Integration | Component | my-component', {
  beforeEach() {
    this.registry.register('component:link-to-external', LinkToExternalComponent);
  },
});
```

which alleviates the assertion failure:

> Assertion Failed: A helper named 'link-to-external' could not be found

but results in a type error:

> TypeError: owner._getExternalRoute is not a function

being thrown from line 16 of the link component:

https://github.com/dgeb/ember-engines/blob/master/addon/-private/link-to-external-component.js#L16

**Comment by krisselden** [comment] 2016-09-13 23:15
@nickiaconis likely missing an injection onto it, the add-on should extend the Engine setupRegistry

**Comment by krisselden** [comment] 2016-09-13 23:19
@nickiaconis it looks like you could just import the engine's initializer and call it once, this will pull in all the extensions

**Comment by krisselden** [comment] 2016-09-13 23:26
Try adding `import "ember-engines/initializers/engines";` to see if that fixes it. That maybe racy though will Engine already has been created, you need to import it early in the tests, if there was some test helper everything pulled in, likely though if engines add-on is going to reopen ember it should be the onLoad hook not an initializer.

**Comment by rwjblue** [comment] 2016-09-14 00:26
The addon should just export `app/components/link-to.js` and `app/components/link-to-external.js` instead of manually registering.

**Comment by rwjblue** [comment] 2016-09-14 00:56
I believe #200 should fix this issue.

**Comment by scalvert** [comment] 2016-09-14 19:57
Failing integration test that identifies the issue.

https://github.com/scalvert/ember-engines/commit/e1b4e7358287720018e8d077266b44b8e1538d1c

Results in:

```
Error: Assertion Failed: A helper named "link-to-external" could not be found
```

**Comment by dgeb** [comment] 2016-09-21 01:48
Closed via #205

**Closed by dgeb** 2016-09-21 01:48 UTC

**Comment by john-bai** [comment] 2019-08-09 16:30
A duplicate issue was filed for this issue after the fix and is still open: #448. Can someone speak to the required setup to not encounter this issue after the fix landed?

**Comment by john-bai** [comment] 2019-08-09 18:37
I couldn’t reproduce the issue now with a new engine I created following the guide, so there’s some issue in my other engine. Doing a diff now of the relevant config/test helper files

**Comment by Leooo** [comment] 2020-02-26 15:53
```javascript
import LinkToExternalComponent from 'ember-engines/components/link-to-external-component';
moduleForComponent('confirmation-appointment-display', 'Integration | Component | confirmation-appointment-display', {
  integration: true,
  beforeEach() {
    this.registry.register('component:link-to-external', LinkToExternalComponent);
  }
});

**Comment by amk221** [comment] 2020-05-07 16:18
This is still an issue with a fresh ember app, here is an example repo with a failing test

https://github.com/amk221/-ember-link-to-external-not-found/commit/5220c64f1c155a17e6207cb8a64ed6a7802ca8eb

Please can you reopen it?

**Comment by lougreenwood** [comment] 2020-07-02 07:38
I just hit this issue too...

**Comment by jonchay** [comment] 2021-01-07 21:01
This seems to still be an issue. Setting up the tests as described in the docs:
```
const modulePrefix = 'engine-name';
const resolver = engineResolverFor(modulePrefix);
```

**Comment by Leooo** [comment] 2021-01-08 09:57
Following is working on our side (on Ember 3.12):

```javascript

import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit'
import LinkToExternalComponent from 'ember-engines/components/link-to-external-component';

module('Integration | Component | next payment action', function (hooks) {
  setupRenderingTest(hooks/*, {resolver: engineResolverFor('ukh-web-engine-payments')}*/);

  hooks.beforeEach(function () {
    this.owner.register('component:link-to-external', LinkToExternalComponent);
    this.owner.lookup('router:main').setupRouter();
  });
 test('dual fuel accounts with no premise', async function (assert) {/*..*/});
});

```

**Comment by ezy** [comment] 2021-01-29 00:21
Having come from working on Jest where common methodology is stubbing components that are dependancies but not required in the test, I followed the same approach in my Ember integration test. Was a nice easy way to get around the error.

```javascript
hooks.beforeEach(function(assert) {
    const externalLinkStub = class LinkToExternalComponent extends Component {};
    this.owner.register('component:link-to-external', externalLinkStub);
  });
```
