### ISSUE TITLE
Helper not found

### ISSUE THREAD

**Issue by ritesh83** [dgeb/ember-engines#242] opened 2016-10-27 17:43 UTC
Are template helpers suppose to work inside ember engines?

I installed the ember-route-action-helper addon and I'm get the following error:
Assertion Failed: A helper named 'route-action' could not be found

I also tried another addon that has a template helper and I get the same could not be found error.

**Comment by knownasilya** [comment] 2016-10-27 18:31
@ritesh83 you need to make sure that the addon is listed in the `dependencies` in `package.json`.

**Comment by nathanhammond** [comment] 2016-10-27 18:35
... in `package.json` of the _engine_.

I'm closing this issue as likely not a bug; being closed doesn't mean that we're ignoring the thread, however. Please stop by [#-ember-engines](https://embercommunity.slack.com/messages/-ember-engines/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) as we all hang out there.

**Closed by nathanhammond** 2016-10-27 18:35 UTC

**Comment by ritesh83** [comment] 2016-10-27 18:36
Thanks @knownasilya @nathanhammond its working now!
