### ISSUE TITLE
Ember Engine Resolver does not find component installed via "ember install addon"

### ISSUE THREAD

**Issue by alexmasita** [dgeb/ember-engines#189] opened 2016-09-03 17:21 UTC
Dear Ember Engines team.  

Great work.  I developed an addon that encapsulates some css and js files and I wanted to include that in my ember-engines application however, on visiting a route "http://localhost:4200/reservation/admin/access/login" that uses the addon component, I get the following error: "A helper named "admin-lte" could not be found".

Though this addon fails my ember-engines app, it successfully gets found when used in a new ember application created through "ember new", which leads me to suspect that perhaps the ember-engines resolver has probably not been adopted to find components added to ember-engines via "Ember install addon-name"?

I am working with the following releases:

(a). ember cli version: "2.7.0"
(b). ember-data: "2.7.0"
(c). ember: "2.7.2"
(d). node: "0.12.7"
(e). npm: "2.11.3"
(f). os: "darwin x64 El Capitan"
(g) jquery: "2.2.4"

**Comment by nathanhammond** [comment] 2016-09-03 18:10
What version of the ember-engines addon are you using?

I suspect that inside of the engine's `package.json` you need to declare a dependency on the addon. We also very intentionally isolate scopes, so what you're describing actually sounds like a feature, not a bug. 😄

I'm closing this issue but _please feel encouraged to reopen it_ if upon further investigation on your side you discover that it may in fact be a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

Ember and Ember CLI have committed to supporting the [Node.js LTS schedule](https://github.com/nodejs/LTS#lts-schedule) for the `HEAD` of our `master` branch(es). This means that we will will drop support for 0.10 on 2016-10-01 and 0.12 on 2016-12-31 per the Node.js Long-term Support Working Group's schedule.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-engines/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if you find yourself still having issues; this is likely easier to work through synchronously. Also, if you can create a publicly postable reproduction of the behavior we'd be better-equipped to tell you what is going on.

**Closed** 2016-09-03 18:10 UTC

**Comment by alexmasita** [comment] 2016-09-03 18:33
Hi Nathanhammond.  Thanks for your quick response.  Well, since I am using ember 2.7.0, I have "ember-engines": "0.2.11" installed as per your documentation.

So, how do you  declare a dependency inside of the engine's package.json?

I have shared the repository on bitbucket with you on this email: github.com@nathanhammond.com.

If you clone and run ember serve on the repo, please visit the following: http://localhost:4200/reservation/admin/access/login. (have configured the dummy the load the engine as you will see through this.mount).

You will see what I am talking about.  The addon that has the js and css I wanted to use is on npm as admin-lte-css-js.  This addon is the one that has the component "admin-lte" which fails to be discovered in the ember-engines application I have just shared with you.

Let me know your thoughts and many thanks.

**Comment by nathanhammond** [comment] 2016-09-03 18:45
It did the right thing for top-level dependencies, but this is something we need to make more clear inside of Ember CLI. I'll take that as a note for our meeting next week.

**Comment by bartocc** [comment] 2018-02-13 10:35
I am having the same issue today with ember-engines 0.5.14.

I've added the "semantic-ui-ember" addon with `yarn add semantic-ui-ember`, which adds it to the 'dependencies' block.

This addon provides a component named 'ui-accordion' for example. I am able to use this component in a template of the host app, but not in a template provided by the engine.

**Comment by bartocc** [comment] 2018-02-13 12:54
I should RTFM to myself!

My index.js file was not configured to use EngineAddon as described in the section [Sharing Components and More](http://ember-engines.com/guide/sharing-components-and-more) of the guides.

Things just worked after that
