### ISSUE TITLE
engine aware generators

### ISSUE THREAD

**Issue by eccegordo** [dgeb/ember-engines#222] opened 2016-10-12 07:48 UTC
- ember cli 2.8.0
- ember js 2.8.2
- ember engines 0.3.4

I believe there are some corner cases where blueprints/generators are not sufficiently aware of engines and can create some unexpected collisions.

Compare these two commits in a contrived example project. The first commit creates an
`The Broccoli Plugin: [TemplateCompiler]` error.

- [[BROKEN] ember g route about -ir collision-engine](https://github.com/eccegordo/collision-example-host/commit/a76486c16a816fed36315c24ad06f91607ad198e)

- [[FIX] remove generated template about.js](https://github.com/eccegordo/collision-example-host/commit/5af331c128cbd9ad578d076dcdc2d77ff08f3c72)

The fix is to remove the duplicate template inside the engine.
`lib/collision-engine/app/templates/about.js`

Because broccoli doesn't like the fact that it collides with `app/templates/about.hbs`

This is logical behavior for addons. But perhaps counter intuitive if the expectation is that generators "just work".

What is the long term plan for generators in ember cli and engines? 
Will engines provide hooks that other blueprints can tie into? 

Presumably some of the major generators need to be updated to handle corner cases when using engines.

**Comment by nathanhammond** [comment] 2016-10-13 09:05
@eccegordo I believe this is a duplicate of https://github.com/ember-cli/ember-cli/issues/5336. Can you confirm? If not I'll reopen.

**Closed by nathanhammond** 2016-10-13 09:05 UTC

**Comment by eccegordo** [comment] 2016-10-14 00:40
@nathanhammond yes that looks to be the same problem. Thanks.
