### ISSUE TITLE
findAll is not a function

### ISSUE THREAD

**Issue by ynnoj** [dgeb/ember-engines#218] opened 2016-10-03 10:20 UTC
I'm trying to do a basic `store` request on the `application` route of my Ember Engine add-on, but parent app is tripping up on the below.

`Error while processing route: products.index this.get(...).findAll is not a function TypeError: this.get(...).findAll is not a function`

``` js
import Ember from 'ember';

const { Route } = Ember;

export default Route.extend({
  model() {
    return this.get('store').findAll('product');
  }
});
```

What is strange is that I can see the `GET` request return the expected data in the network tab.
- ember-cli 2.8.0 
- ember 2.8.0
- ember-engines 0.3.0

The engine is a separate add-on I set up following the repo guides and functions as expected if I remove the `findAll`. The `store` dependency is defined in the engine and parent app.

**Comment by mydea** [comment] 2016-10-03 11:10
For me, it helped to manually inject the store service in the engine:

```js
export default Route.extend({
  store: inject.service(),
  model() { /* ... */ }
});
```

After declaring it as a dependency on the engine.

**Comment by ynnoj** [comment] 2016-10-03 12:38
@mydea Thank you! Perhaps we should update the documentation to include this?

**Comment by trentmwillis** [comment] 2016-11-19 23:41
If you have to manually inject the `store` then that means your Engine isn't running the Initializers from Ember Data (such as [this one](https://github.com/emberjs/data/blob/fdc4b2d5845f10d7e26b2296198851ea54a3dbfe/addon/-private/initializers/store-injections.js#L11-L14)). Closing as this isn't particularly an issue with Engines, just a setup problem.

**Closed by trentmwillis** 2016-11-19 23:41 UTC

**Comment by Dhaulagiri** [comment] 2016-11-19 23:45
Do you know what setup problem this indicates?

**Comment by trentmwillis** [comment] 2016-11-19 23:47
As noted above, the problem is that the initializers aren't running. This could happen for a myriad of reasons. Two most common would be that you're either not properly using `loadInitializers` in your `engine.js` file or you have don't have the initializers included in your application's namespace.

**Comment by Dhaulagiri** [comment] 2016-11-20 00:21
Interesting. My engine setup was working and then I started having this same problem myself. I'll revisited my config to see what might be wrong.

**Comment by ynnoj** [comment] 2016-11-21 16:09
@trentmwillis Thanks, I'll take a look the app setup.

**Comment by cibernox** [comment] 2016-11-21 17:08
As @mydea mentions, I fixed this by explicitly injecting the store in the routes and doing `this.get('store')` instead of `this.store`.

It turns out that all routes have a `store` property on them with a `find` method, I have no idea why.

**Comment by rwjblue** [comment] 2016-11-22 01:10
Basically: legacy, we should remove...

**Comment by dbollinger** [comment] 2017-02-08 19:00
I am unclear about what the current resolution is here-- do we need to continue manually injecting the store into our engine routes for the time being? I'm using Ember/Data/Cli 2.11 and Engines 0.4.

**Comment by zigahertz** [comment] 2017-02-25 00:30
Encountering the same issue, although I've included `store` as a dependency for my engine both in `app.js` and in the engine's `engine.js`, I still have to manually inject the store into routes for the engine, or else it cannot find models in the application store.

ember v2.8.3
ember-engines v0.3.4
